[package]
name = "zee-grammar"
version = "0.1.0"
authors = ["Marius Cobzarenco <marius@reinfer.io>"]
description = "Wrappers for tree sitter grammars used by zee"
homepage = "https://github.com/mcobzarenco/zee/tree/master/grammar"
license = "Apache-2.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
tree-sitter = "0.6.3"

[build-dependencies]
cc = "1.0.47"
tree-sitter = "0.6.3"
